steps:
 - name: 'python:3.11'
   entrypoint: 'bash'
   args:
    - '-c'
    - |
      cd pthon-appbuid 
      echo " welcome to python app"
      python new_app.py
      echo "this is the end --"

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "10s"